version: '2'
services:
  zaxh-rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq/data:/var/lib/rabbitmq
      - ./data/rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    restart: always
    container_name: zaxh-rabbitmq
    hostname: zaxh-rabbitmq